// languages.js
const languages = {
    "zh": {
        "title": "《暗黑》人物关系图",
        "language_label": "选择语言：",
        "timeline_label": "选择时间线：",
        "timeline_options": {
            "all": "全部",
            "1953": "1953",
            "1986": "1986",
            "2019": "2019"
        },
        "music_play": "播放",
        "music_pause": "暂停",
        "nodes": [
            { id: 1, label: "Jonas\n(乔纳斯)", title: "2019年主角" },
            { id: 2, label: "Michael\n(迈克尔/米克尔)", title: "2019年Jonas的父亲，1986年穿越者" },
            { id: 3, label: "Hannah\n(汉娜)", title: "Jonas的母亲" },
            { id: 4, label: "Ines\n(伊内斯)", title: "1986年收养Mikkel" },
            { id: 5, label: "Stranger\n(陌生人)", title: "2019年中年Jonas" },
            { id: 6, label: "Ulrich\n(乌尔里希)", title: "2019年警察，Mikkel的父亲" },
            { id: 7, label: "Katharina\n(卡塔琳娜)", title: "Ulrich的妻子" },
            { id: 8, label: "Martha\n(玛莎)", title: "Ulrich的女儿，Jonas的恋人" },
            { id: 9, label: "Magnus\n(马格努斯)", title: "Ulrich的长子" },
            { id: 10, label: "Tronte\n(特龙特)", title: "Ulrich的父亲" },
            { id: 11, label: "Jana\n(亚娜)", title: "Ulrich的母亲" },
            { id: 12, label: "Mads\n(马兹)", title: "Ulrich的弟弟，1986年失踪" },
            { id: 13, label: "Agnes\n(阿格尼丝)", title: "1953年Tronte的母亲" },
            { id: 14, label: "Charlotte\n(夏洛特)", title: "2019年警察局长" },
            { id: 15, label: "Peter\n(彼得)", title: "Charlotte的丈夫" },
            { id: 16, label: "Elisabeth\n(伊丽莎白)", title: "Charlotte的小女儿" },
            { id: 17, label: "Helge\n(黑尔格)", title: "2019/1986/1953年，绑架者" },
            { id: 18, label: "Bernd\n(伯恩德)", title: "Helge的父亲，核电站创始人" },
            { id: 19, label: "Franziska\n(弗兰齐丝卡)", title: "Charlotte的大女儿" },
            { id: 20, label: "Claudia\n(克劳迪娅)", title: "1986年核电站负责人" },
            { id: 21, label: "Regina\n(雷吉娜)", title: "2019年旅馆老板" },
            { id: 22, label: "Aleksander\n(亚历山大)", title: "Regina的丈夫" },
            { id: 23, label: "Bartosz\n(巴托什)", title: "Regina的儿子" },
            { id: 24, label: "Egon\n(埃贡)", title: "1986/1953年警察" },
            { id: 25, label: "Noah\n(诺亚)", title: "2019/1986/1953年神秘牧师" },
            { id: 26, label: "Tannhaus\n(塔恩豪斯)", title: "1986年钟表匠，时间机器制造者" }
        ],
        "edges": [
            { from: 1, to: 2, label: "父子" },
            { from: 2, to: 3, label: "夫妻" },
            { from: 4, to: 2, label: "养母" },
            { from: 1, to: 5, label: "未来自己" },
            { from: 6, to: 2, label: "父子" },
            { from: 6, to: 7, label: "夫妻" },
            { from: 6, to: 8, label: "父女" },
            { from: 6, to: 9, label: "父子" },
            { from: 10, to: 6, label: "父子" },
            { from: 10, to: 11, label: "夫妻" },
            { from: 10, to: 12, label: "父子" },
            { from: 13, to: 10, label: "母子" },
            { from: 1, to: 8, label: "恋人" },
            { from: 14, to: 15, label: "夫妻" },
            { from: 14, to: 16, label: "母女" },
            { from: 14, to: 19, label: "母女" },
            { from: 17, to: 15, label: "父子" },
            { from: 18, to: 17, label: "父子" },
            { from: 20, to: 21, label: "母女" },
            { from: 21, to: 22, label: "夫妻" },
            { from: 21, to: 23, label: "母子" },
            { from: 24, to: 20, label: "父女" },
            { from: 17, to: 25, label: "助手" },
            { from: 23, to: 25, label: "合作者" },
            { from: 5, to: 26, label: "时间机器提供者" },
            { from: 26, to: 20, label: "技术顾问" }
        ]
    },
    "ja": {
        "title": "『ダーク』キャラクター関係図",
        "language_label": "言語を選択：",
        "timeline_label": "タイムラインを選択：",
        "timeline_options": {
            "all": "すべて",
            "1953": "1953",
            "1986": "1986",
            "2019": "2019"
        },
        "music_play": "再生",
        "music_pause": "一時停止",
        "nodes": [
            { id: 1, label: "Jonas\n(ジョナス)", title: "2019年の主人公" },
            { id: 2, label: "Michael\n(マイケル/ミッケル)", title: "2019年ジョナスの父、1986年の穿越者" },
            { id: 3, label: "Hannah\n(ハンナ)", title: "ジョナスの母" },
            { id: 4, label: "Ines\n(イネス)", title: "1986年にミッケルを養子にする" },
            { id: 5, label: "Stranger\n(見知らぬ人)", title: "2019年の中年ジョナス" },
            { id: 6, label: "Ulrich\n(ウルリッヒ)", title: "2019年の警官、ミッケルの父" },
            { id: 7, label: "Katharina\n(カタリーナ)", title: "ウルリッヒの妻" },
            { id: 8, label: "Martha\n(マルタ)", title: "ウルリッヒの娘、ジョナスの恋人" },
            { id: 9, label: "Magnus\n(マグヌス)", title: "ウルリッヒの長男" },
            { id: 10, label: "Tronte\n(トロンテ)", title: "ウルリッヒの父" },
            { id: 11, label: "Jana\n(ヤナ)", title: "ウルリッヒの母" },
            { id: 12, label: "Mads\n(マッズ)", title: "ウルリッヒの弟、1986年失踪" },
            { id: 13, label: "Agnes\n(アグネス)", title: "1953年トロンテの母" },
            { id: 14, label: "Charlotte\n(シャルロッテ)", title: "2019年の警察署長" },
            { id: 15, label: "Peter\n(ペーター)", title: "シャルロッテの夫" },
            { id: 16, label: "Elisabeth\n(エリザベート)", title: "シャルロッテの末娘" },
            { id: 17, label: "Helge\n(ヘルゲ)", title: "2019/1986/1953年、誘拐者" },
            { id: 18, label: "Bernd\n(ベルント)", title: "ヘルゲの父、核電廠創設者" },
            { id: 19, label: "Franziska\n(フランツィスカ)", title: "シャルロッテの長女" },
            { id: 20, label: "Claudia\n(クラウディア)", title: "1986年の核電廠責任者" },
            { id: 21, label: "Regina\n(レギーナ)", title: "2019年の旅館経営者" },
            { id: 22, label: "Aleksander\n(アレクサンダー)", title: "レギーナの夫" },
            { id: 23, label: "Bartosz\n(バルトシュ)", title: "レギーナの息子" },
            { id: 24, label: "Egon\n(エゴン)", title: "1986/1953年の警官" },
            { id: 25, label: "Noah\n(ノア)", title: "2019/1986/1953年の謎の牧師" },
            { id: 26, label: "Tannhaus\n(タンハウス)", title: "1986年の時計職人、タイムマシン製作者" }
        ],
        "edges": [
            { from: 1, to: 2, label: "父子" },
            { from: 2, to: 3, label: "夫婦" },
            { from: 4, to: 2, label: "養母" },
            { from: 1, to: 5, label: "未来の自分" },
            { from: 6, to: 2, label: "父子" },
            { from: 6, to: 7, label: "夫婦" },
            { from: 6, to: 8, label: "父女" },
            { from: 6, to: 9, label: "父子" },
            { from: 10, to: 6, label: "父子" },
            { from: 10, to: 11, label: "夫婦" },
            { from: 10, to: 12, label: "父子" },
            { from: 13, to: 10, label: "母子" },
            { from: 1, to: 8, label: "恋人" },
            { from: 14, to: 15, label: "夫婦" },
            { from: 14, to: 16, label: "母女" },
            { from: 14, to: 19, label: "母女" },
            { from: 17, to: 15, label: "父子" },
            { from: 18, to: 17, label: "父子" },
            { from: 20, to: 21, label: "母女" },
            { from: 21, to: 22, label: "夫婦" },
            { from: 21, to: 23, label: "母子" },
            { from: 24, to: 20, label: "父女" },
            { from: 17, to: 25, label: "助手" },
            { from: 23, to: 25, label: "協力者" },
            { from: 5, to: 26, label: "タイムマシン提供者" },
            { from: 26, to: 20, label: "技術顧問" }
        ]
    },
    "en": {
        "title": "Dark Character Relationship Chart",
        "language_label": "Select Language:",
        "timeline_label": "Select Timeline:",
        "timeline_options": {
            "all": "All",
            "1953": "1953",
            "1986": "1986",
            "2019": "2019"
        },
        "music_play": "Play",
        "music_pause": "Pause",
        "nodes": [
            { id: 1, label: "Jonas", title: "2019 Protagonist" },
            { id: 2, label: "Michael", title: "Jonas' Father in 2019, Time Traveler from 1986" },
            { id: 3, label: "Hannah", title: "Jonas' Mother" },
            { id: 4, label: "Ines", title: "Adopted Mikkel in 1986" },
            { id: 5, label: "Stranger", title: "Middle-aged Jonas in 2019" },
            { id: 6, label: "Ulrich", title: "2019 Police Officer, Mikkel's Father" },
            { id: 7, label: "Katharina", title: "Ulrich's Wife" },
            { id: 8, label: "Martha", title: "Ulrich's Daughter, Jonas' Lover" },
            { id: 9, label: "Magnus", title: "Ulrich's Eldest Son" },
            { id: 10, label: "Tronte", title: "Ulrich's Father" },
            { id: 11, label: "Jana", title: "Ulrich's Mother" },
            { id: 12, label: "Mads", title: "Ulrich's Brother, Missing in 1986" },
            { id: 13, label: "Agnes", title: "Tronte's Mother in 1953" },
            { id: 14, label: "Charlotte", title: "2019 Police Chief" },
            { id: 15, label: "Peter", title: "Charlotte's Husband" },
            { id: 16, label: "Elisabeth", title: "Charlotte's Youngest Daughter" },
            { id: 17, label: "Helge", title: "Kidnapper in 2019/1986/1953" },
            { id: 18, label: "Bernd", title: "Helge's Father, Nuclear Plant Founder" },
            { id: 19, label: "Franziska", title: "Charlotte's Eldest Daughter" },
            { id: 20, label: "Claudia", title: "1986 Nuclear Plant Manager" },
            { id: 21, label: "Regina", title: "2019 Hotel Owner" },
            { id: 22, label: "Aleksander", title: "Regina's Husband" },
            { id: 23, label: "Bartosz", title: "Regina's Son" },
            { id: 24, label: "Egon", title: "Police Officer in 1986/1953" },
            { id: 25, label: "Noah", title: "Mysterious Priest in 2019/1986/1953" },
            { id: 26, label: "Tannhaus", title: "1986 Clockmaker, Time Machine Creator" }
        ],
        "edges": [
            { from: 1, to: 2, label: "Father-Son" },
            { from: 2, to: 3, label: "Husband-Wife" },
            { from: 4, to: 2, label: "Adoptive Mother" },
            { from: 1, to: 5, label: "Future Self" },
            { from: 6, to: 2, label: "Father-Son" },
            { from: 6, to: 7, label: "Husband-Wife" },
            { from: 6, to: 8, label: "Father-Daughter" },
            { from: 6, to: 9, label: "Father-Son" },
            { from: 10, to: 6, label: "Father-Son" },
            { from: 10, to: 11, label: "Husband-Wife" },
            { from: 10, to: 12, label: "Father-Son" },
            { from: 13, to: 10, label: "Mother-Son" },
            { from: 1, to: 8, label: "Lovers" },
            { from: 14, to: 15, label: "Husband-Wife" },
            { from: 14, to: 16, label: "Mother-Daughter" },
            { from: 14, to: 19, label: "Mother-Daughter" },
            { from: 17, to: 15, label: "Father-Son" },
            { from: 18, to: 17, label: "Father-Son" },
            { from: 20, to: 21, label: "Mother-Daughter" },
            { from: 21, to: 22, label: "Husband-Wife" },
            { from: 21, to: 23, label: "Mother-Son" },
            { from: 24, to: 20, label: "Father-Daughter" },
            { from: 17, to: 25, label: "Assistant" },
            { from: 23, to: 25, label: "Collaborator" },
            { from: 5, to: 26, label: "Time Machine Provider" },
            { from: 26, to: 20, label: "Technical Advisor" }
        ]
    }
};